File system
uncoma-curza-lab/backend-sistema-concursos pull request #130
Opened 2023-09-08 14:48 UTC by liaima

2023-09-11 17:27 UTC, fkmurphy requested changes
Cuidado con el PDF y JPG que quedó en el PR

2023-09-26 04:02 UTC, fkmurphy commented on src/app/controllers/PersonalFileController.php
> +                }
Cada objeto podría retornar la Url o el arreglo que le pertenece a la vista.

2023-09-26 04:06 UTC, fkmurphy commented on src/app/controllers/PersonalFileController.php
> +        }
Cada modelo podría entender cómo obtener los DocumentType que le pertenecen.

$file->getDocumentTypes()

2023-09-26 04:13 UTC, fkmurphy commented on src/app/controllers/PersonalFileController.php
> +    }
Proteger, podría ser con los behaviors de AccessControl. Pero hay que verificar si es un usuario.

2023-09-26 04:13 UTC, fkmurphy commented on src/app/controllers/PersonalFileController.php
> +    }
Faltaría proteger a todos creo.

2023-09-26 04:18 UTC, fkmurphy commented on src/app/models/PersonalFile.php
> +        if($this->validationStatus() === self::VALIDATION_STATUES[self::VALID_WITH_UNTIL_DATE]){
Hay un typo -> `VALIDATION_STATUES`

2023-09-26 04:20 UTC, fkmurphy commented on src/app/views/personal-file/_files_list.php
> +              if($file->validationStatus() === PersonalFile::VALIDATION_STATUES[PersonalFile::UNVALIDATED]){
Idem typo `VALIDATION_STATUES`

2023-09-26 04:23 UTC, fkmurphy commented on src/app/views/postulations/postulation_files.php
> -    <iframe src="<?= $shareUrl ?>" width="100%" height="350px" title="Postualtion Files Iframe">
una belleza, chau iframe 🤝

2023-09-26 04:24 UTC, fkmurphy reviewed
Dejé algunos comentarios, cualquier cosa si ves que le pifié en algo o no se entiende lo charlamos

2023-09-26 20:37 UTC, liaima commented on src/app/models/PersonalFile.php
> +        if($this->validationStatus() === self::VALIDATION_STATUES[self::VALID_WITH_UNTIL_DATE]){
VALIDATION_STATUSES

2023-10-04 20:18 UTC, fkmurphy commented on src/app/migrations/m231002_194825_load_personal_files_documents_types.php
> +    */
Esto se puede borrar

2023-10-04 20:23 UTC, fkmurphy commented on src/app/views/personal-file/_files_list.php
> +              if($file->getValidationStatusName() === PersonalFile::VALIDATION_STATUSES[PersonalFile::UNVALIDATED]){
Creo que acá sigue pasando lo mismo que charlamos. Diría que deberías tener un método que te indique si posee un estado o no, no haría esta comparación acá. El método `getValidationStatusName` lo tendría únicamente para mostrarlo por pantalla (no como comparativa)

2023-10-20 12:56 UTC, fkmurphy reviewed
-

2024-03-13 13:16 UTC, closed without merging