Iframe nextcloud
uncoma-curza-lab/backend-sistema-concursos pull request #42
Opened 2022-05-23 03:17 UTC by liaima

2022-05-23 12:45 UTC, fkmurphy commented on .env_example
> +NEXTCLOUD_DIR=Concursos
pondría todo minúscula

2022-05-23 12:45 UTC, fkmurphy commented on .envcloud
> +SPC_API_URL=https://apps.curza.uncoma.edu.ar/api/v1
Esto lo necesita el ambiente de nextcloud?

2022-05-23 12:47 UTC, fkmurphy commented on bin/yii.sh
> +fi
Bueno, es una posible solución al tema de los permisos. Habría que sacarlo hacia un PR aparte

2022-05-23 12:48 UTC, fkmurphy commented on docker-compose.override.yml-example
> -
es un archivo draft para preparar el ambiente local, no lo borraría

2022-05-23 12:49 UTC, fkmurphy commented on docker-compose.yml
> +
No levantaría 2 DB para todos los casos, en el caso del desarrollo local, es preferible tener un solo motor de bases de datos.

2022-05-23 12:52 UTC, fkmurphy commented on .gitignore
> +postgresdataclud/*
Cuidado, el nombre de la carpeta en el compose de docker es postgresdatacloud

2022-05-23 12:54 UTC, fkmurphy commented on src/app/controllers/PostulationsController.php
> +            'person' => $user->identity->person,
excelente, este es un fix medio aparte. Siempre que se pueda, es mejor hacer un fix de otro tema en otra branch y crear el PR para que podamos mergearlo más rápido.

2022-05-23 12:57 UTC, fkmurphy commented on src/app/models/InscriptionForm.php
> +        }
En cualquier ocasión retornas `false`. No hacen falta 2 else.

2022-05-23 13:01 UTC, fkmurphy commented on src/app/models/Postulations.php
> +        if($today < $this->contest->end_date){
El `end_date` pertenece a la finalización del concurso.
Creo que por el momento usaríamos el enrollment_end_date (creo que se llamaba así el campo).
Este último tiene que ver con el fin de las inscripciones y por lo tanto, no puede modificar la info que subió.

2022-05-23 13:03 UTC, fkmurphy commented on src/app/services/NextcloudService.php
> +        $user = \Yii::$app->params['nextcloud']['username'];
Qué te parece si esto lo llevamos al constructor de esta clase?

2022-05-23 13:05 UTC, fkmurphy commented on src/app/views/contests/details.php
> +    <?= Html::button('<i class="bi bi-person-plus-fill"></i> Postularse', [
Ojo, esto ya está integrado en master

2022-05-23 13:06 UTC, fkmurphy commented on src/app/views/postulations/postulation_files.php
> +//-------------------------------------------
Si ya no lo estás usando, borremos los comments estos tmb

2022-05-23 13:08 UTC, fkmurphy requested changes
Muy bueno!! :rocket: 
Dejé algunos comments que serían más o menos interesantes resolverlos antes de mergear.

2022-05-23 21:45 UTC, liaima commented on .env_example
> +NEXTCLOUD_DIR=Concursos
Lo hice y olvide cambiarlo en el example

2022-05-23 21:46 UTC, liaima commented on .envcloud
> +SPC_API_URL=https://apps.curza.uncoma.edu.ar/api/v1
hecho

2022-05-23 21:46 UTC, liaima commented on .envcloud
> +SPC_API_URL=https://apps.curza.uncoma.edu.ar/api/v1
No, error mio, arme un .env para cloud y olvide ponerlo en uso...

2022-05-23 21:47 UTC, liaima commented on bin/yii.sh
> +fi
Ok. ahora vemos como se haría eso...

2022-05-23 21:48 UTC, liaima commented on docker-compose.override.yml-example
> -
Mala mia, cambie el nombre en lugar de copiarlo... resuelto

2022-05-23 21:49 UTC, liaima commented on docker-compose.yml
> +
Okok dale, lo vemos en la meet

2022-05-23 21:51 UTC, liaima commented on .gitignore
> +postgresdataclud/*
Ups, yo y mi tipeo en ingles... es horrible

2022-05-23 22:00 UTC, liaima commented on docker-compose.yml
> +    env_file: .env
Mala mia, lo cree y olvide aplicarlo...

2022-05-24 22:10 UTC, fkmurphy commented on docker-compose.override.yml-example
> +      - 5400:5432
antes de mergear sacar esta db

2022-05-24 22:12 UTC, fkmurphy commented on docker-compose.yml
> +      #     restart: always
no veo necesario sacar el `restart: always`, pero en dicho caso, entonces es mejor eliminar la linea

2022-05-24 22:15 UTC, fkmurphy commented on .envcloud
> +
Esto está bien, lo único que debería crearse un example y omitir este para no commitearlo.

2022-05-24 22:18 UTC, fkmurphy commented on src/app/controllers/PostulationsController.php
> +        if($response['code'] == 100){
es exactamente 100?

2022-05-24 22:27 UTC, fkmurphy commented on src/app/views/postulations/my_postulations.php
> +                            '<span class="bi bi-folder-fill" aria-hidden="true"></span>',
aca se puede agregar el title para que ya lo tenga

2022-05-24 22:27 UTC, fkmurphy approved these changes
Excelente, dejé unos comments de detalle.

2022-05-24 23:26 UTC, merged